[tools]
claude = "latest"
codex = "latest"
gh = "latest"
go = "latest"
k9s = "latest"
kubectl = "latest"
node = "latest"
pi = "latest"

[settings]
trusted_config_paths = ["~/Work"]
minimum_release_age = "24h"

[settings.upgrade]
auto_prune = true
